[package]
name = "bookkeeper"
version = "0.1.0"
edition = "2021"

[dependencies]
archive-reader = "0.3.5"
clap = { version = "4.5.4", features = ["derive"] }
lopdf = "0.32.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
sha1 = "0.10.6"
walkdir = "2.5.0"
